# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Set up Doxygen   
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'src/main/resources'
    - name: Test with Maven
      run: mvn test -DargLine="-Dcontiperf.active=false"
    # Ensure that there is a docs folder in the repo
    - name: Ensure docs dir exists
      run: mkdir docs
    - name: Generate documentation
      run: mvn doxygen:report
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: docs # The branch the action should deploy to.
        folder: target/doxygen # The folder the action should deploy.
